import { ArrowLeft, ExternalLink, Leaf, Sprout } from "lucide-react";
import Link from "next/link";

export default function TreeDedicationPage() {
  return (
    <main className="tree-page">
      <nav className="site-nav" aria-label="Main navigation">
        <Link className="wordmark" href="/#top" aria-label="Robert Dickinson memorial home"><span className="wordmark-mark">∞</span><span>Robert Dickinson</span></Link>
        <div className="nav-links"><Link href="/#life">His life</Link><Link href="/#legacy">Scientific legacy</Link><Link href="/#events">Events</Link><Link href="/#gallery">Gallery</Link><Link href="/#memories">Memories</Link></div>
        <Link className="nav-cta" href="/#share">Share a memory</Link>
      </nav>
      <header id="top" className="tree-page-hero">
        <div><p className="section-kicker light">A living tribute</p><h1>Let Robert’s memory grow.</h1><p>Dedicate trees in Robert E. Dickinson’s name and support native reforestation—an enduring tribute to a scientist whose work helped us understand the living Earth.</p><a className="tree-primary-action" href="https://onetreeplanted.org/products/gift-trees-in-memory" target="_blank" rel="noopener noreferrer"><Sprout size={19} /> Dedicate trees in Robert’s memory <ExternalLink size={15} /></a><small>Continues to One Tree Planted, an independent 501(c)(3) nonprofit.</small></div>
        <aside className="tree-hero-card"><Leaf size={42} aria-hidden="true" /><strong>Robert E. Dickinson</strong><em>1940–2026</em><p>Born in Ohio and raised in Minnesota, Robert devoted his life to understanding the connections among land, atmosphere, water, vegetation, and climate.</p></aside>
      </header>
      <section className="tree-how" aria-labelledby="tree-how-title"><div className="tree-section-heading"><p className="section-kicker">How it works</p><h2 id="tree-how-title">A thoughtful dedication in three steps</h2><p>The nonprofit provider handles the planting and sends the keepsake materials directly.</p></div><div className="tree-step-grid"><article><span>01</span><h3>Choose the number of trees</h3><p>Select one or more trees to be planted in Robert’s memory where restoration is most needed.</p></article><article><span>02</span><h3>Personalize the tribute</h3><p>Enter Robert E. Dickinson as the honoree, write a memorial message, and choose an e-card design and delivery date.</p></article><article><span>03</span><h3>Receive a certificate</h3><p>A personalized certificate recognizes the dedication, and project updates help show the wider reforestation impact.</p></article></div></section>
      <section className="tree-project"><div><p className="section-kicker light">Minnesota connection</p><h2>The Chippewa National Forest</h2><p>Robert grew up in Minnesota. The Chippewa National Forest project restores jack pine, black spruce, red pine, eastern white pine, and northern white cedar while strengthening wildlife habitat and forest resilience.</p><a href="https://www.memorialtree.com/chippewa-national-forest-project" target="_blank" rel="noopener noreferrer">Explore the Chippewa restoration project <ExternalLink size={15} /></a></div><div className="tree-project-note"><strong>Good to know</strong><p>The dedication provider plants where restoration is most needed. The Chippewa link explains a Minnesota project connected to Robert’s story, but it does not guarantee that a particular gift tree will be planted there.</p></div></section>
      <section className="tree-faq" aria-labelledby="tree-faq-title"><div className="tree-section-heading"><p className="section-kicker">Questions</p><h2 id="tree-faq-title">Before you dedicate</h2></div><details open><summary>Will I receive a certificate?</summary><p>Yes. One Tree Planted states that donors receive a personalized tree certificate with the honoree’s name.</p></details><details><summary>Can I include a personal message?</summary><p>Yes. The dedication flow includes a custom Tree-Card message, image choice, and delivery date.</p></details><details><summary>Will I know the exact tree location?</summary><p>The gift supports native reforestation projects where trees are most needed. It represents a living forest tribute rather than an individually marked tree.</p></details><details><summary>Is the donation tax-deductible?</summary><p>One Tree Planted is a U.S. 501(c)(3). Tax treatment depends on your circumstances; keep the provider’s receipt for your records.</p></details></section>
      <section className="tree-final-cta"><Sprout size={42} aria-hidden="true" /><h2>Plant hope. Preserve memory.</h2><p>Continue to the provider when you are ready to create Robert’s dedication.</p><a className="tree-primary-action" href="https://onetreeplanted.org/products/gift-trees-in-memory" target="_blank" rel="noopener noreferrer">Begin the dedication <ExternalLink size={15} /></a></section>
      <footer className="site-footer"><div className="wordmark footer-mark"><span className="wordmark-mark">∞</span><span>Robert E. Dickinson</span></div><p>Created with love by his academic community.</p><div className="footer-links"><Link href="/"><ArrowLeft size={14} /> Return to memorial</Link></div></footer>
    </main>
  );
}
