export const treeUiDefaults: Record<string, string> = {
  "tree.ui.heroButton": "Choose a place ↓",
  "tree.ui.recordShortcut": "Already donated? Record my trees →",
  "tree.ui.totalLabel": "Trees dedicated",
  "tree.ui.totalDedication": "in Robert’s memory",
  "tree.ui.totalNote": "Reported by contributors after donating.",
  "tree.ui.stepChoose": "Choose a place",
  "tree.ui.stepDonate": "Donate with the provider",
  "tree.ui.stepRecord": "Record your tribute",
  "tree.ui.featuredIntro": "Honor Robert’s Minnesota roots by supporting forest restoration.",
  "tree.ui.placesIntro": "Choose a landscape that holds meaning for you.",
  "tree.ui.aboutProjects": "About these projects",
  "tree.ui.recordHeading": "Already donated?",
  "tree.ui.recordHeadingLine2": "Record your trees.",
  "tree.ui.recordIntro": "No account needed. Takes about 30 seconds.",
  "tree.ui.formName": "Your name",
  "tree.ui.formProject": "Planting project",
  "tree.ui.formChoose": "Choose your project",
  "tree.ui.formCount": "Number of trees",
  "tree.ui.formOptional": "Add a donation reference (optional)",
  "tree.ui.formReference": "Confirmation / order no.",
  "tree.ui.formConfirm": "I have completed my donation.",
  "tree.ui.formSubmit": "Record my trees →",
  "tree.ui.formNote": "Only record the tree quantity confirmed by your provider.",
  "tree.ui.faqHeading": "Questions about tree counts and payments",
  "tree.ui.returnHeading": "Finished your payment?",
  "tree.ui.returnIntro": "Return here to record the trees or restoration gift.",
  "tree.ui.returnButton": "Record my contribution →",
  "tree.ui.footerHome": "Return to memorial",
  "tree.ui.footerTop": "Return to top ↑",
  "tree.ui.expand": "Project details",
  "tree.ui.faqQuestion6": "Will I receive a certificate?",
  "tree.ui.faqAnswer6": "If your selected planting program offers a certificate, you will receive it directly from the provider. Check the certificate and dedication options at checkout, and enter Robert E. Dickinson’s name where available. Certificate availability, format, and delivery vary by program; not every provider offers one. Recording your trees on this website does not issue a provider certificate.",
  "tree.ui.faqQuestion1": "Does the memorial website handle my payment?",
  "tree.ui.faqAnswer1": "No. Payment takes place entirely on the selected provider’s website. The memorial stores only the contribution record you report afterward and never receives your card or banking credentials.",
  "tree.ui.faqQuestion2": "About the landscape images",
  "tree.ui.faqAnswer2": "The landscape artwork evokes the regions connected to Robert’s life. It does not depict or guarantee a specific planting site.",
  "tree.ui.faqQuestion3": "How are tree totals and locations counted?",
  "tree.ui.faqAnswer3": "After successful payment, report the exact tree quantity shown by the provider. We record both that quantity and the geographic level the provider actually guarantees: exact forest/project, state/region, or where needed most.",
  "tree.ui.faqQuestion4": "What if the provider does not state an exact number of trees?",
  "tree.ui.faqAnswer4": "The gift is preserved as a restoration contribution but is not converted into an estimated number of trees.",
  "tree.ui.faqQuestion5": "What if the provider I chose will not accept my international payment?",
  "tree.ui.faqAnswer5": "Use the universal One Tree Planted route or another accessible exact-tree option. The trees still count in Robert’s lifetime total; they are simply attributed to the location level the provider can honestly support.",
  "tree.form.route.chippewa-arbor-day": "Chippewa National Forest · Arbor Day Foundation",
  "tree.form.geography.chippewa-arbor-day": "Exact forest: Chippewa National Forest",
  "tree.form.route.minnesota-living-tribute": "Minnesota forests · A Living Tribute",
  "tree.form.geography.minnesota-living-tribute": "State-level attribution: Minnesota (specific forest not guaranteed)",
  "tree.form.route.global-one-tree-planted": "Where needed most · One Tree Planted",
  "tree.form.geography.global-one-tree-planted": "Global / greatest-need attribution; not assigned to a Robert-specific location",
  "tree.form.route.brazil-black-jaguar": "Brazil · Black Jaguar Foundation",
  "tree.form.geography.brazil-black-jaguar": "Regional attribution: Araguaia corridor · Amazon–Cerrado",
  "tree.form.route.arizona-living-tribute": "Arizona forests · A Living Tribute",
  "tree.form.geography.arizona-living-tribute": "State-level attribution: Arizona",
  "tree.form.route.georgia-living-tribute": "Georgia forests · A Living Tribute",
  "tree.form.geography.georgia-living-tribute": "State-level attribution: Georgia",
  "tree.form.route.texas-living-tribute": "Texas forests · A Living Tribute",
  "tree.form.geography.texas-living-tribute": "State-level attribution: Texas",
  "tree.form.route.colorado-csfs": "Colorado · Colorado State Forest Service",
  "tree.form.geography.colorado-csfs": "State-level attribution: Colorado",
  "tree.form.route.california-living-tribute": "California forests · A Living Tribute",
  "tree.form.geography.california-living-tribute": "State-level attribution: California",
  "tree.form.route.massachusetts-tree-boston": "Boston, Massachusetts · Tree Boston",
  "tree.form.geography.massachusetts-tree-boston": "City-level attribution: Boston, Massachusetts",
  "tree.form.route.new-england-neff": "New England · NEFF restoration gift",
  "tree.form.geography.new-england-neff": "Regional attribution: New England",
  "tree.ui.formNamePlaceholder": "Name for your tribute",
  "tree.ui.formBusy": "Recording…",
  "tree.ui.formLocation": "Location recorded:",
  "tree.ui.formSuccessTrees": "Thank you — your contribution has been successfully recorded. Your trees are now included in Robert’s living-tribute total.",
  "tree.ui.formSuccessGift": "Thank you — your contribution has been successfully recorded in Robert’s living tribute.",
  "tree.ui.formError": "Unable to record the tribute. Please try again.",
  "tree.ui.formUnavailable": "Dedication reporting is temporarily unavailable.",
  "tree.ui.formGuidanceGift": "This provider does not assign a defensible exact tree quantity. Your successful gift will be preserved as a forest-restoration contribution and will not be converted into a guessed number of trees.",
  "tree.ui.formGuidanceBoston": "Choose one of Tree Boston’s listed one-tree options ($100, $500, or $1,000), then record 1 tree. Other donation amounts should not be converted into a tree count.",
  "tree.ui.formGuidanceTrees": "Enter only the exact number of trees stated by the provider or, for Colorado’s official fund, the quantity implied by its published $2-per-seedling conversion.",
  "tree.ui.restorationTotal": "Plus {count} forest-restoration gifts",
  "tree.ui.returnSelected": "You chose {project}. Return here to record the trees or restoration gift."
};
