// Refresh the reviewed copy only when it still matches the previous wording.
// New text saved through the manager passes through unchanged.
const revisions: Record<string, string> = {
  "Robert Earl Dickinson helped change how humanity understands the living Earth.\n\nBorn in Millersburg, Ohio, and raised in Minnesota, Robert carried an expansive curiosity into a lifetime of science. He studied chemistry and physics at Harvard University, graduating in 1961, then turned to meteorology at the Massachusetts Institute of Technology, earning his master’s degree in 1962 and Ph.D. in 1966.\n\nHe joined the National Center for Atmospheric Research in 1968. Early in his career, he advanced understanding of how planetary waves transfer energy through the atmosphere. Later, as a leader in NCAR’s Climate and Global Dynamics Division, he confronted a central weakness in the era’s climate models: land was treated largely as a passive store of water. Robert helped recast it as a dynamic system of soils, plants, water, energy, and carbon.\n\nThat insight reshaped global climate modeling. His pioneering work brought vegetation and land-surface processes into climate models and helped establish the intellectual foundations of modern Earth-system science. Across six decades, his research connected atmospheric dynamics with hydrology, drought, remote sensing, aerosols, tropical deforestation, and the terrestrial carbon cycle.\n\nRobert held professorships at the University of Arizona and Georgia Tech before joining The University of Texas at Austin in 2008. At UT’s Jackson School of Geosciences, he was known not only as a giant of climate science, but as a patient and exacting mentor. After retiring from UT in 2018, he continued as a Distinguished Professor in Residence at UCLA, remaining active in research, collaboration, and mentorship.\n\nHis deepest legacy lives in both the models that now describe a more complete Earth and the people he trained to ask better questions of it.": "Robert Earl Dickinson helped change how humanity understands the living Earth.\n\nBorn in Millersburg, Ohio, and raised in Minnesota, Robert carried an expansive curiosity into a lifetime of science. He studied chemistry and physics at Harvard University, graduating in 1961, then turned to meteorology at the Massachusetts Institute of Technology, earning his master’s degree in 1962 and Ph.D. in 1966.\n\nRobert was known as a patient and exacting mentor. He gave care and attention to students, postdoctoral scholars, and visiting scientists, and valued the people he worked with as much as the questions they explored together.\n\nHis career took him from MIT and NCAR to the University of Arizona, Georgia Tech, UT Austin, and UCLA. After retiring from UT Austin, he remained active in collaboration and mentorship. Curiosity, physical insight, and generosity continued to shape his conversations with colleagues across generations.",
  "S.M. in Meteorology (1962), Ph.D. in Meteorology (1966), then Research Associate (1966–1968).": "S.M. (1962) and Ph.D. (1966) in Meteorology; Research Associate through 1968.",
  "Scientist (1968–1975), Head of the Climate Section (1975–1981), and Deputy Director of the Climate and Global Dynamics Division (1981–1990).": "Scientist, Climate Section Head, and Deputy Director of Climate and Global Dynamics.",
  "Professor of Atmospheric Sciences (1990–1993), then Regents Professor (1993–1999), with appointments spanning atmospheric physics, hydrology, and tree-ring research.": "Professor of Atmospheric Sciences, then Regents Professor.",
  "Professor in Earth and Atmospheric Sciences and Georgia Power/Georgia Research Alliance Endowed Chair.": "Professor of Earth and Atmospheric Sciences; Georgia Power/Georgia Research Alliance Endowed Chair.",
  "Professor in the Jackson School of Geosciences, continuing research in climate, land-surface processes, drought, remote sensing, and Earth-system science.": "Professor in the Jackson School of Geosciences.",
  "Distinguished Professor in Residence in the Department of Atmospheric and Oceanic Sciences, continuing scientific collaboration and mentorship.": "Distinguished Professor in Residence in Atmospheric and Oceanic Sciences.",
  "Bob’s scientific career took shape at MIT. He completed his Ph.D. in Meteorology in 1966 with Propagators of Atmospheric Motions, then remained at MIT as a research associate through 1968. His early work centered on a fundamental problem in atmospheric dynamics: how planetary-scale waves propagate through the atmosphere, and how they interact with the circulation around them. In a remarkable series of papers, he showed that the spherical geometry of the Earth matters fundamentally for planetary-wave propagation and how waves can be guided toward critical lines where their energy and momentum are absorbed.": "How do planetary-scale waves move through the atmosphere and interact with its circulation? Robert showed why Earth’s spherical geometry matters for wave propagation, and how atmospheric waveguides direct energy and momentum toward critical lines where they are absorbed.",
  "At the National Center for Atmospheric Research, Bob’s science widened from upper-atmospheric dynamics and planetary atmospheres to global circulation, climate change, and climate modeling. As a scientist, Climate Section head, and deputy director, he helped shape both the models and the community building them.": "Robert connected atmospheric circulation and radiation with the problem of climate change. His work helped make climate models a way to investigate interacting physical processes, while bringing soils, water, and vegetation into their representation of land.",
  "Working across atmospheric science, hydrology, and tree-ring research at Arizona, Bob deepened the physical description of the land surface and helped make those models testable against observations.": "Robert deepened the physical description of the land surface and helped make land models testable against observations. Vegetation, soil moisture, and surface energy exchange became processes that could be measured, compared, and improved.",
  "At Georgia Tech, Bob brought atmospheric physics, hydrology, ecosystems, biogeochemistry, and observations from space into closer conversation. His research and teaching increasingly treated climate as a coupled Earth system rather than a collection of separate components.": "Robert brought atmospheric physics, hydrology, ecosystems, biogeochemistry, and satellite observations together to study climate as a coupled Earth system. The question became how exchanges of water, energy, and carbon shape one another.",
  "At UT Austin’s Jackson School of Geosciences, Bob continued to connect models with observations while giving unusual care to students, postdoctoral scholars, and visiting scientists.": "Robert used models and observations together to study drought, vegetation stress, soil-moisture feedbacks, and climate extremes. Satellite measurements offered a way to test whether models captured the behavior of the living land.",
  "After retiring from UT Austin, Bob continued as a Distinguished Professor in Residence in UCLA’s Department of Atmospheric and Oceanic Sciences. He remained engaged in research, collaboration, and mentoring, continuing the habit that had defined his career: moving easily across disciplines while returning to first principles.": "Robert continued to connect ideas across atmospheric science and Earth-system modeling, returning to first principles as new models and observations emerged. Collaboration and mentorship carried that approach into the work of younger scientists.",
  "His life": "His Life",
  "Scientific legacy": "Scientific Legacy",
  "His story": "His Life",
  "The story of a scientist who kept widening the questions he asked—and the circle of people he welcomed into them.": "Robert’s beginnings, his path through life, and the curiosity and generosity colleagues remember.",
  "A chronological journey through the institutions, questions, and enduring ideas that shaped Robert’s work.": "The questions Robert asked, the ideas he advanced, and the ways his work changed our understanding of Earth.",
  "Career chapters": "Scientific contributions",
  "Across every institution": "Ideas that connect his work",
  "The affiliations mark chapters in Robert’s career. These ideas reveal the deeper continuity running through them.": "These research threads connect Robert’s discoveries across decades, from atmospheric motion to the coupled Earth system."
};

export function reviseEditorialText(value: string): string {
  return revisions[value] ?? value;
}
